spring.application.name=lld

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=2s

rate-limit.enabled=true
rate-limit.fail-open=false

rate-limit.token-bucket[0].endpoint=/api/login
rate-limit.token-bucket[0].capacity=5
rate-limit.token-bucket[0].refill-rate-per-second=1.0

rate-limit.sliding-window-log[0].endpoint=/api/search
rate-limit.sliding-window-log[0].max-requests=10
rate-limit.sliding-window-log[0].window-size-ms=60000

rate-limit.sliding-window-counter[0].endpoint=/api/profile
rate-limit.sliding-window-counter[0].max-requests=5
rate-limit.sliding-window-counter[0].window-size-ms=60000

rate-limit.fixed-window-counter[0].endpoint=/api/fixed
rate-limit.fixed-window-counter[0].max-requests=3
rate-limit.fixed-window-counter[0].window-size-ms=60000

rate-limit.leaky-bucket[0].endpoint=/api/export
rate-limit.leaky-bucket[0].capacity=3
rate-limit.leaky-bucket[0].leak-rate-per-second=1.0
